### ISSUE TITLE
Code implementation of results from history

### ISSUE THREAD

**Issue by Danishan2** [jkcsoftwaresllp/CasGamPro_client#26]
### Feature Summary

This component will pop-up, when we click on the history winner icon

### Problem Statement

![image](https://github.com/user-attachments/assets/3d172f36-7a9c-4947-8a82-1c33b0de4f47)

### Proposed Solution

The component will consist of multiple sub-components, some of which have already been created while others need to be designed as discussed during the MEET-18 session. Your task is to organize these sub-components systematically and proceed with further implementation.

### Benefits

This Final Component will used in multiple Game Sections

### Acceptance Criteria

- [X] Specific, measurable criteria for success

### Additional Context

Discussed on MEET-18

**Comment by rishxbh81** [comment]
![Image](https://github.com/user-attachments/assets/af9b136e-99b1-4e6a-96de-3d20f92cfcdb)
current status
