### ISSUE TITLE
Card Design 

### ISSUE THREAD

**Issue by Danishan2** [jkcsoftwaresllp/CasGamPro_client#27]
### Feature Summary

Code Implementation of Card of Deck

### Problem Statement

The component must be dynamic in nature and capable of receiving a `cardCode` prop. Using this `cardCode`, it should dynamically extract the necessary information about the card details (such as card number, card color, card suit) and generate the card at runtime accordingly.  

Refer to the attached images for context and structure of the card details. The design should ensure that the component adapts dynamically to the extracted data to create and display the card seamlessly.

![image](https://github.com/user-attachments/assets/bc520795-3540-4b19-9576-94f8e581518c)
![image](https://github.com/user-attachments/assets/bfcaa415-d9d6-4199-9644-3600242a1a57)

### Proposed Solution

Discussed in MEET-16

### Benefits

Will used everywhere in the Project

### Acceptance Criteria

- [X] Specific, measurable criteria for success

### Additional Context

Referee the discussion on MEET-16

**Comment by Salman-jkc** [comment]
Images:


![BetOnCard_Lock](https://github.com/user-attachments/assets/537f4fb4-75f7-463f-83e1-ca9ca8cd92f2)
![Card](https://github.com/user-attachments/assets/f823694b-ef3d-4e74-af1f-c5abe73b749b)
![BetInCircle](https://github.com/user-attachments/assets/53db5acf-f120-41f9-b6b7-159c60fca3e6)
![BetInCircle_dark](https://github.com/user-attachments/assets/79a1dc53-f16a-4c3b-b22f-d9e7af4bec71)
![BetOnCard](https://github.com/user-attachments/assets/6505c2d4-21d6-4123-8aac-f9c14bb7c6d6)
![BetOnCard_Dard_Lock](https://github.com/user-attachments/assets/d1c51429-4557-44d0-b22f-b412cb91dc11)
![BetOnCard_Dark](https://github.com/user-attachments/assets/1c0213a5-c232-4d00-bb01-526fe1255127)
