### ISSUE TITLE
Card Section

### ISSUE THREAD

**Issue by Danishan2** [jkcsoftwaresllp/CasGamPro_client#28]
### Feature Summary

Code Implementation of Card Section

### Problem Statement

The is the section where scanned cards from the video will be visible.

![image](https://github.com/user-attachments/assets/49ac372c-cb8b-43bc-ae5e-8e72a88168b1)

### Proposed Solution

As we discussed on MEET-18

### Benefits

This component will show in every game 

### Acceptance Criteria

- [X] Specific, measurable criteria for success

### Additional Context

Refer the discussion of MEET-18

**Comment by Salman-jkc** [comment]
![Image](https://github.com/user-attachments/assets/832647f4-e989-4980-90fc-aa6bd5555db5)
![Image](https://github.com/user-attachments/assets/fe639b14-cb43-4687-a50e-0b10e2c63298)
